CREATE DATABASE procedures_triggers;
USE procedures_triggers;
-- EMP TABLE
CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(20),
    JOB VARCHAR(20),
    MGR INT,
    HIREDATE DATE,
    SAL DECIMAL(7,2),
    COMM DECIMAL(7,2),
    DEPTNO INT
);
-- EMP DATA
INSERT INTO EMP VALUES
(7369,'Laxman1','CLERK',7902,'1980-12-17',800,NULL,20),
(7499,'ALLEN','SALESMAN',7698,'1981-02-20',1600,300,30),
(7521,'Laxman2','SALESMAN',7698,'1981-02-22',1250,500,30),
(7566,'JONES','MANAGER',7839,'1981-04-02',2975,NULL,20),
(7698,'Laxman3','MANAGER',7839,'1981-05-01',2850,NULL,30),
(7782,'CLARK','MANAGER',7839,'1981-06-09',2450,NULL,10),
(7788,'Laxman4','ANALYST',7566,'1982-12-09',3000,NULL,20),
(7839,'KING','PRESIDENT',NULL,'1981-11-17',5000,NULL,10),
(7844,'Laxman5','SALESMAN',7698,'1981-09-08',1500,0,30),
(7876,'ADAMS','CLERK',7788,'1983-01-12',1100,NULL,20),
(7900,'Laxman6','CLERK',7698,'1981-12-03',950,NULL,30),
(7902,'FORD','ANALYST',7566,'1981-12-03',3000,NULL,20),
(7934,'Laxman7','CLERK',7782,'1982-01-23',1300,NULL,10);
-- PROCEDURE 1: NO PARAMETERS
DELIMITER //
CREATE PROCEDURE GetAllEmployees()
BEGIN
    SELECT ENAME, JOB, SAL
    FROM EMP;
END //
DELIMITER ;
-- PROCEDURE 2: IN PARAMETER
DELIMITER //
CREATE PROCEDURE GetEmployeesByDept(IN p_deptno INT)
BEGIN
    SELECT ENAME, JOB, SAL
    FROM EMP
    WHERE DEPTNO = p_deptno;
END //
DELIMITER ;
-- PROCEDURE 3: OUT PARAMETER
DELIMITER //
CREATE PROCEDURE GetDeptSalaryTotal(
    IN p_deptno INT,
    OUT p_total DECIMAL(10,2)
)
BEGIN
    SELECT SUM(SAL) INTO p_total
    FROM EMP
    WHERE DEPTNO = p_deptno;
END //
DELIMITER ;
-- PROCEDURE 4: IF STATEMENT
DELIMITER //
CREATE PROCEDURE GiveRaise(
    IN p_empno INT,
    IN p_pct DECIMAL(5,2)
)
BEGIN
    DECLARE v_sal DECIMAL(7,2);
    SELECT SAL INTO v_sal
    FROM EMP
    WHERE EMPNO = p_empno;
    IF v_sal < 2000 THEN
        UPDATE EMP
        SET SAL = SAL + (SAL * p_pct / 100)
        WHERE EMPNO = p_empno;
    ELSE
        UPDATE EMP
        SET SAL = SAL + (SAL * (p_pct / 2) / 100)
        WHERE EMPNO = p_empno;
    END IF;
END //
DELIMITER ;
-- TRIGGER 1: BEFORE INSERT
DELIMITER //
CREATE TRIGGER trg_check_salary
BEFORE INSERT ON EMP
FOR EACH ROW
BEGIN
    IF NEW.SAL < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Salary cannot be negative';
    END IF;
END //
DELIMITER ;
-- AUDIT TABLE
CREATE TABLE EMP_AUDIT (
    audit_id INT AUTO_INCREMENT PRIMARY KEY,
    empno INT,
    old_sal DECIMAL(7,2),
    new_sal DECIMAL(7,2),
    changed_on DATETIME
);
-- TRIGGER 2: AFTER UPDATE
DELIMITER //
CREATE TRIGGER trg_log_sal_change
AFTER UPDATE ON EMP
FOR EACH ROW
BEGIN
    IF OLD.SAL <> NEW.SAL THEN
        INSERT INTO EMP_AUDIT(
            empno,
            old_sal,
            new_sal,
            changed_on
        )
        VALUES (
            OLD.EMPNO,
            OLD.SAL,
            NEW.SAL,
            NOW()
        );
    END IF;
END //
DELIMITER ;
-- TRIGGER 3: BEFORE DELETE
DELIMITER //
CREATE TRIGGER trg_prevent_manager_delete
BEFORE DELETE ON EMP
FOR EACH ROW
BEGIN
    IF OLD.JOB = 'PRESIDENT' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Cannot delete the president record';
    END IF;
END //
DELIMITER ;
-- EXECUTE PROCEDURES
CALL GetAllEmployees();
CALL GetEmployeesByDept(20);
CALL GetDeptSalaryTotal(30, @total);
SELECT @total;
CALL GiveRaise(7369, 10);
-- CHECK AUDIT TRIGGER
SELECT * FROM EMP_AUDIT;
-- MANAGE PROCEDURES
SHOW PROCEDURE STATUS
WHERE Db = 'procedures_triggers';
SHOW CREATE PROCEDURE GetAllEmployees;
-- MANAGE TRIGGERS
SHOW TRIGGERS;
SHOW TRIGGERS
WHERE `Table` = 'EMP';